apiVersion: v1
kind: Service
metadata:
  name: control-center
  labels:
    service: control-center
spec:
  selector:
    service: control-center
  ports:
    - port: 9021
      protocol: TCP
      targetPort: 9021
