apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    service: postgres
spec:
  selector:
    service: postgres
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
      
