apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    service: postgres
spec:
  containers:
    - name: postgres
      image: postgres:16.1-alpine
      env:
        - name: POSTGRES_USER
          value: "dsuser@PDIRDB00"
        - name: POSTGRES_PASSWORD
          value: "dspass@PDIRDB00"
        - name: POSTGRES_DB
          value: "PDIRDB00"
      ports:
        - containerPort: 5432
      resources:
        requests:
          memory: 1Gi
          cpu: 250m
        limits:
          memory: 1Gi
          cpu: 250m
