apiVersion: v1
kind: Pod
metadata:
  name: schema-registry
  labels:
    service: schema-registry
spec:
  containers:
    - name: schema-registry
      image: confluentinc/cp-schema-registry:7.4.3
      env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: "schema-registry"
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: "kafka:29092"
        - name: SCHEMA_REGISTRY_LISTENERS
          value: "http://0.0.0.0:8081"
      ports:
        - containerPort: 8081