apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  labels:
    service: schema-registry
spec:
  selector:
    service: schema-registry
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081