apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  labels:
    service: zookeeper
spec:
  containers:
    - name: zookeeper
      image: confluentinc/cp-zookeeper:7.4.3
      env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
      ports:
        - containerPort: 2181
