clients:
  my-account: 'localhost:5000/my-account'
  agora: 'localhost:5000/agora'

kafka-config:
  server-url: localhost:9092
  schema-registry-url: http://localhost:8081
  group-id: 'integration-service-local'
  concurrency: 5
  topics:
    request-data:
      name: 'poc-request-data-local'
    exception-messages:
      name: 'poc-exception-messages-local'
      ttl-in-days: 1
    my-account-data:
      name: 'poc-pdir-my-account-data-local'
      ttl-in-days: 1
    agora-data:
      name: 'poc-pdir-agora-data-local'
      ttl-in-days: 1