clients:
  my-account: 'origin-service:5000/my-account'
  agora: 'origin-service:5000/agora'

kafka-config:
  server-url: kafka:29092
  schema-registry-url: http://schema-registry:8081
  group-id: 'integration-service-docker'
  concurrency: 5
  topics:
    request-data:
      name: 'poc-pdir-request-data-docker'
    exception-messages:
      name: 'poc-pdir-exception-messages-docker'
      ttl-in-days: 1
    my-account-data:
      name: 'poc-pdir-my-account-data-docker'
      ttl-in-days: 1
    agora-data:
      name: 'poc-pdir-agora-data-docker'
      ttl-in-days: 1