version: '3.9'

services:
  app:
    image: integration-service-app:latest
    container_name: integration-service-app
    build:
      context: ./
      args:
        - JAR_FILE=build/libs/\*.jar
    tty: true
    stdin_open: true
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - poc-ir-bra_local-network
    ports:
      - "4000:4000"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          memory: 128M

networks:
  poc-ir-bra_local-network:
    external: true
